addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip, testbuild.zip]
    target_paths: 4ad5d3c6-969e-4618-a871-24bde8b98f52
jdk: [oraclejdk8]
language: java
script: [mvn install, ./df-build.sh]
sudo: 'false'
# Modified by Insights Service at 2016-04-05 06:45:55.767091
